---
title: "Unbonding Queue Analysis: Simulation"
author: "Jonas Gehrlein"
date: "2024-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
block_to_days <- function(block_future, block_current){
  return((block_future - block_current) * 6 / 60 / 60 / 24 )
}
```

```{r}
initialize_simulation <- function(max_stake, back_of_unbonding_queue_block, current_block_number){
  GLOBAL_MAX_STAKE <<- max_stake
  GLOBAL_CURRENT_BACK_OF_UNBONDING_QUEUE_BLOCK <<- back_of_unbonding_queue_block
  GLOBAL_CURRENT_BLOCK <<- current_block_number
}

run_simulation <- function(unbonding_stake, current_block_number) {
  GLOBAL_CURRENT_BLOCK <<- current_block_number
  
  # Calculate unbonding time delta
  unbonding_time_delta <- unbonding_stake / GLOBAL_MAX_STAKE * 403200
  
  GLOBAL_CURRENT_BACK_OF_UNBONDING_QUEUE_BLOCK <<- min(
  GLOBAL_CURRENT_BLOCK + 403200, 
  max(GLOBAL_CURRENT_BLOCK, GLOBAL_CURRENT_BACK_OF_UNBONDING_QUEUE_BLOCK) + round(max(unbonding_time_delta, 1),0)
)

  # Calculate the unbonding block number
  unbonding_block_number <- min(403200, max(GLOBAL_CURRENT_BACK_OF_UNBONDING_QUEUE_BLOCK - GLOBAL_CURRENT_BLOCK, 28800)) + GLOBAL_CURRENT_BLOCK
  
  return(paste0("The unbonding time will be at block number ", unbonding_block_number, 
                " or in ", unbonding_block_number - GLOBAL_CURRENT_BLOCK, " blocks (",  
                round(block_to_days(unbonding_block_number, GLOBAL_CURRENT_BLOCK), digits = 1), " days).",
                " The Global Back of the queue is at ", GLOBAL_CURRENT_BACK_OF_UNBONDING_QUEUE_BLOCK))
}
```



```{r}
initialize_simulation(1000, 0, 0)
# Queue Voll
run_simulation(3000, 0)
run_simulation(1, 403200/2) # 403603
run_simulation(100, 0)
run_simulation(100, 0)
run_simulation(100, 0)
```

